{% set name = "pyosf" %}
{% set version = "1.0.5" %}
{% set sha256 = "76cea8fbecca11cbc4055f9d9342e3166c4c1db32cc8352d6dafa9b2a4d0fb2d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-{{sha256}}.zip
  url: https://github.com/psychopy/pyosf/archive/v{{version}}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - requests
    - pytest-runner
  run:
    - python
    - requests

test:
  imports:
    - pyosf
    - pyosf.remote
    - pyosf.local
    - pyosf.project

about:
  home: https://github.com/psychopy/pyosf
  license: MIT
  license_family: MIT
  license_file: "The MIT License (MIT).md"
  summary: 'A pure Python library for simple file sync with Open Science Framework'

  description: |
    This package is for simple synchronisation of files from the local file space to the Open Science Framework (OSF). There is a more complex fully-featured sync package by the Center for Open Science, who created OSF, called osf-sync

extra:
  recipe-maintainers:
    - kastman
