travis:
  secure:
    BINSTAR_TOKEN: PO2lB4BJ1Z4UEbV8B575u+J8iB2uBF+PMU1i4CNEuf6aa2Xo/VtVEObA9E4FSTXzJM7sGpedRJKUJT/WuI/ue2vFxy4wrTLZXGu4yF1JMgOYocJF0MVJqovnYLrA1ygxJdWX60cW/TkYjB5+TKgJTxltOCcSSMX0lUqk5gKjc9dF6jf2iC16or0rtJ/sAlj+haFfu/KilercVWS58YU+aPgwv1jRiw69w4akOQA+6WrtrF/8950ZYH/Sn96UUvJjbY6FNFDMQlWodnenZxgk8Qh14RQhmqvYochrDG7fFRtSUnIEqFHQM9x8+clmKdc2oc3NTqyCJQklO0E0t4H8FWybQG67+5BdBlAIlwc6kCNLAfUiL7DcbJNw6ato2dDjNEck4BNsuDAnxU5HU2gJ7knhG6dEPfrHrj6IOglxm2X1yyil77jRL9xOhWWd0BbV52FWKnn+XG0hAkLbns9Ok0PxBJq4JtG0xTVhgEmAdfqwL6vRaNqjo8zGagC5vSiYn2Bh5WgXUYxZhAK2idiDWJQ71Nm1nFv0pvvvj8YcBCWG2VG1BAWt0GZFfiOCYiWBigaUPhYsusCnmc/amv9GpwoMuZA33ZQ1w/07nlLJXX900N4ORHFsAl7yNR59RqfmYcWmzyPVImOOxbvVbsRuJ3V/1o4R6MyFe69iiMDk7qg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
